// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3lYbLQEB9lH25DRwBy5rZecg1_MIjcZ4',
    appId: '1:124105466023:web:4f851a19eced85f608bb82',
    messagingSenderId: '124105466023',
    projectId: 'firstproject-af5b8',
    authDomain: 'firstproject-af5b8.firebaseapp.com',
    storageBucket: 'firstproject-af5b8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGXiX4ervx4Y1VSE7oALpCYxXjD-WpY6c',
    appId: '1:124105466023:android:28fee4314a5e6a0608bb82',
    messagingSenderId: '124105466023',
    projectId: 'firstproject-af5b8',
    storageBucket: 'firstproject-af5b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhvmNbm-YcJOIDDqx0Q6MIV7f_PfYQvY',
    appId: '1:124105466023:ios:45948278049a17d008bb82',
    messagingSenderId: '124105466023',
    projectId: 'firstproject-af5b8',
    storageBucket: 'firstproject-af5b8.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhvmNbm-YcJOIDDqx0Q6MIV7f_PfYQvY',
    appId: '1:124105466023:ios:45948278049a17d008bb82',
    messagingSenderId: '124105466023',
    projectId: 'firstproject-af5b8',
    storageBucket: 'firstproject-af5b8.firebasestorage.app',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3lYbLQEB9lH25DRwBy5rZecg1_MIjcZ4',
    appId: '1:124105466023:web:de788605579530c508bb82',
    messagingSenderId: '124105466023',
    projectId: 'firstproject-af5b8',
    authDomain: 'firstproject-af5b8.firebaseapp.com',
    storageBucket: 'firstproject-af5b8.firebasestorage.app',
  );

}